// <auto-generated />
using System;
using BBSSystem.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace BBSSystem.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(BBSSystemDbContext))]
    [Migration("20240924120205_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("BrowseTimes")
                        .HasColumnType("bigint");

                    b.Property<string>("CloseUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreateUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IsClose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IsReview")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("是否已审核（T/F）");

                    b.Property<DateTime>("LastReplyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastReplyUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastReplyUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostLevelId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostTypeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("ReplyTimes")
                        .HasColumnType("bigint");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TopTypeId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PostTypeId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.PostType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PostTypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PostType");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Reply", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CloseUserId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HeadUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IsClose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IsMasterReply")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("是否是帖子内容（T/F）");

                    b.Property<string>("IsReview")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("是否已审核（T/F）");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuoteReplyContent")
                        .HasColumnType("longtext");

                    b.Property<string>("QuoteReplyId")
                        .HasColumnType("longtext");

                    b.Property<string>("QuoteReplyUserId")
                        .HasColumnType("longtext");

                    b.Property<string>("ReplyContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Section", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PostAllCount")
                        .HasColumnType("bigint");

                    b.Property<long>("PostTodayCount")
                        .HasColumnType("bigint");

                    b.Property<string>("PostTypeInfo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("当前板块中包含的所有发帖类型和数量");

                    b.Property<string>("SectionDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SectionIcon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SectionPlaybill")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("板块海报");

                    b.Property<string>("SectionTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.SectionLordUserMapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionLordUserMapping");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Post", b =>
                {
                    b.HasOne("BBSSystem.Domain.PostInfo.PostType", "PostType")
                        .WithMany()
                        .HasForeignKey("PostTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PostType");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.SectionLordUserMapping", b =>
                {
                    b.HasOne("BBSSystem.Domain.PostInfo.Section", null)
                        .WithMany("SectionLords")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Section", b =>
                {
                    b.Navigation("SectionLords");
                });
#pragma warning restore 612, 618
        }
    }
}
