// <auto-generated />
using System;
using BBSSystem.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace BBSSystem.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(BBSSystemDbContext))]
    [Migration("20240909100647_up1")]
    partial class up1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.MySql)
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Section", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PostAllCount")
                        .HasColumnType("bigint");

                    b.Property<long>("PostTodayCount")
                        .HasColumnType("bigint");

                    b.Property<string>("PostTypeInfo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("当前板块中包含的所有发帖类型和数量");

                    b.Property<string>("SectionDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SectionIcon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SectionPlaybill")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("板块海报");

                    b.Property<string>("SectionTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.SectionLordUserMapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SectionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionLordUserMapping");
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.SectionLordUserMapping", b =>
                {
                    b.HasOne("BBSSystem.Domain.PostInfo.Section", null)
                        .WithMany("SectionLords")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BBSSystem.Domain.PostInfo.Section", b =>
                {
                    b.Navigation("SectionLords");
                });
#pragma warning restore 612, 618
        }
    }
}
